/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-112938-g12e25af7a8-20231210"
#endif /* AVUTIL_FFVERSION_H */
